#######################
# Config: Development #
#######################
# (production settings go in _config.build.yml)

name: The Curious Sage Adventure
url: 'http://curioussage.com'
description: What the hell are you two going to do with 28 acres and an RV, anyway?
timezone: America/Los_Angeles
googleanalytics: UA-26097728-8
authors:
  - name: Aki Rose
    email: hi@akiro.se
    github: gesa
    twitter: gesa
    twitterid: 9321562
  - name: Mark
share:
  width: 1200
  size: 1200
  image: 'img/share.jpg'
  twitterText: These two fools went on an adventure.

exclude: ['img']

###########
# Content #
###########

future: true
show_drafts: true
permalink: /:categories/:year:month:day/:title/

#############
# Compiling #
#############

highlighter: rouge

markdown: kramdown
kramdown:
  auto_ids: true
#  input: GFM

defaults:
  -
    scope:
      path: ''
    values:
      layout: 'post'

navigation:
  - url: /homestead/
    title: Homesteading
  - url: /rv/
    title: RV Life
  - url: /about/
    title: About M & A
  - url: /where-we-went/
    title: Our Travels
