#################################################
# Config: Development                           #
#################################################
# (production settings go in _config.build.yml) #

#############
# Meta info #
#############

name: The Curious Sage Adventure
url: 'http://curioussage.com'
description: What the hell are you two going to do with 28 acres and an RV, anyway?
timezone: America/Los_Angeles
googleanalytics: UA-26097728-8
authors:
  - name: Aki Rose
    email: hi@akiro.se
    github: gesa
    twitter: gesa
    twitterid: 9321562
  - name: Mark

share:
  width: 1200
  size: 1200
  image: 'img/share.jpg'
  twitterText: These two fools went on an adventure.

#############
# Authoring #
#############

future: true
show_drafts: true
permalink: /:categories/:year/:title/

defaults:
  -
    scope:
      path: ''
    values:
      layout: 'post'

collections:
  root:
    output: true
    permalink: /:title

#############
# Compiling #
#############

exclude:    ['css', 'js', 'img']
keep_files: ['css', 'js', 'img']

highlighter: rouge
markdown: kramdown
kramdown:
  smart_quotes: ["apos", "apos", "quot", "quot"]
  input: GFM
